name: DEPLOY
on:
  push:
    branches:
    - main
  
jobs:
  web-deploy:
    name: auto-deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latets code
    - uses: actions/checkout@v2
    
    - name: Sync files
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete --exclude=".git" --exclude="/public" --exclude=".github"
        path: /
        remote_path: ${{ secrets.DEPLOY_PATH }}
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_port: ${{ secrets.DEPLOY_PORT }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
