name: DEPLOY
on:
  push:
    branches:
      - staging

jobs:
  web-deploy:
    name: auto-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latets code
      - uses: actions/checkout@v2

      - name: Sync files
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete --exclude=".git" --exclude="/public" --exclude=".github"
          path: /
          remote_path: ${{ secrets.DEPLOY_PATH_STAGING }}
          remote_host: ${{ secrets.DEPLOY_HOST_STAGING }}
          remote_port: ${{ secrets.DEPLOY_PORT_STAGING }}
          remote_user: ${{ secrets.DEPLOY_USER_STAGING }}
          remote_key: ${{ secrets.DEPLOY_KEY_STAGING }}
